global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "django"
    metrics_path: "/metrics"
    static_configs:
      # Use 'backend' as it is the service name in docker-compose
      - targets: ["backend:8000"]
